// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * Reports captured step effort without changing the thread's saved settings.
 */
export type ReasoningEffortUpdatedNotification = { threadId: string, turnId: string, reasoningEffort: ReasoningEffort | null,
/**
 * Automatic mode is active, including when a decision falls back to current effort.
 */
adaptive: boolean, };
