// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadUnreadPosition } from "./ThreadUnreadPosition";

/**
 * The first unread position in a durable local thread. A null position means read.
 * The opaque revision guards edits against activity or marks the caller has not seen.
 */
export type ThreadReadState = { firstUnread: ThreadUnreadPosition | null, revision: string, };
